
dotfiles:
  editor: sublime

ssh:
 servers:
   # comments are allowed
   myhostkey: # comments are allowed
     host: 192.168.1.1
     user: myuser
   name: # creates alias ssh + key, i.e. sshname
     host: 192.168.1.2
     user: myuser2

git:
  default:
    branches:
      main: main
      dev: dev
  /Users/username/path/to/the/repo:
    branches:
      main: prod
      dev: develop

#Vagrant boxes
vagrant:
  suspend_before_up: yes
  boxes:
    vvv: ~/vvv
    hs: ~/Homestead

docker:
  containers:
    mydocker: ~/Projects/docker-project/docker
